server:
  port: 8401
spring:
  application:
    name: alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册地址
    sentinel:
      transport:
        dashboard: localhost:8080   #配置Sentinel dash地址
        port: 8719      #默认8719端口，假如被占用会自动冲8719+1开始扫描
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: alibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#web监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true   #激活Sentinel对Feign的支持