server:
  port: 8090
spring:
  application:
    name: eurekaOrder8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka,http://localhost:8081/eureka
  instance:
    instance-id: 127.0.0.1
      #    #访问路径可以显示IP地址
    prefer-ip-address: true
      #    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
      #    #lease-renewal-interval-in-seconds: 1
    #    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #    #lease-expiration-duration-in-seconds: 2